### ISSUE TITLE
Different timers with same time not showing

### ISSUE THREAD

**Issue by NIBI123** [PhenomDevel/PhenomRaidTools#13]
Hey,

if i make a timer and have
Message A be sent after 4 seconds say "Hello"
Message B be sent after 4 seconds say "Hi"
only one will be sent. Can this be fixed possibly?
I havent tested if you can send two messages to two different recievers but i tried sending message A to "ALL" and message B to "Myname" and it only sent one of them

**Comment by PhenomDevel** [comment]
Hey thanks for the report. This will be fixed today. I noticed it myself yesterday during raid and implemented a fix immediatly. Problem lies in the same timings. So it won't work with different receivers either.
