### ISSUE TITLE
Timer Options Not DIsplaying

### ISSUE THREAD

**Issue by rp4rk** [PhenomDevel/PhenomRaidTools#16]
**Describe the bug**
Viewing timers will display an empty window, see screenshots for an example.

**To Reproduce**
1. Go to timers
2. Click on any timer
3. See that the window is not populated with the expected controls

**Expected behavior**
The standard set of timers options is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8212881/106667980-94788b00-65a1-11eb-9c68-dabd7a91cc2e.png)

**Additional context**
Traced to this change, reverting it fixes the problem - https://github.com/PhenomDevel/PhenomRaidTools/commit/9ac08e534e1d4ee487f3786cfeb3b502e8ae6c2d

**Comment by PhenomDevel** [comment]
I added the change for the fucked up backdrops from elvui. You ui looks kinda like elvui. Do you use it and if so have you any additions for evlui? Maybe there is something breaking it. 

Additionally do you have BugSack/BugGrabber installed and can track any kind of exception?

**Comment by PhenomDevel** [comment]
I believe i found the problem. This behavior should be fixed in 
https://github.com/PhenomDevel/PhenomRaidTools/releases/tag/2.0.21.1

**Comment by rp4rk** [comment]
Hey, I use RealUI - it uses Aurora(?) to skin UI frames - I can confirm this behavior is the same on default UI also :)

**Comment by PhenomDevel** [comment]
Yeah i tested it on default ui and fixed it for default so hopes are high it should be fixed for you as well. Let me know if it works now :)

Might take a while until the release is available through curse though.

**Comment by PhenomDevel** [comment]
Did it fix the issue? If so I would close the issue.
