### ISSUE TITLE
Saving Message Template resets its type in rotation

### ISSUE THREAD

**Issue by Hayato2846** [PhenomDevel/PhenomRaidTools#24]
**Describe the bug**
Hey! All of my currently used messages are of type 'Advanced' and i really love the new template system. When i save a message of type 'Advanced' its type is reset to 'Cooldown'. So my current actions are:
1. Click through my messages, save them as template, switch between messages and manually set its type back to 'Advanced'.

**To Reproduce**
1. Save a message of type 'Advanced' as template
2. Switch the message to another and switch back
3. Previously saved message resets its type to 'Cooldown'

**Expected behavior**
Message Type doesn't reset after saving a message.

**Additional context**
P.S.:
I love your addon! :)

**Comment by PhenomDevel** [comment]
Hey! Thanks for the report. 

I believe this behaviour only occurs on messages which were created prior to the templates system. Could you try and create a new message and repeeat the process?

**Comment by PhenomDevel** [comment]
And also please check out 2.2.6.3. This might already fix this issue. This can only be tested with messages create prior to 2.2.6*.

**Comment by Hayato2846** [comment]
Hey!

I can confirm that this behaviour only occurs on messages which were created prior to the templates system.

I'll test the new version as soon as it's up on Wowup (Curse Crawler seems like kinda behind) and will give you feedback :)

Thanks in advance

**Comment by Hayato2846** [comment]
Hey again.

Bug fixed with 2.2.6.3!
