### ISSUE TITLE
Add more sounds

### ISSUE THREAD

**Issue by Hayato2846** [PhenomDevel/PhenomRaidTools#28]
It'd be super cool if we have some more sounds to choose from! It's a really good base of sounds to support Healing CDs but I'm missing things like:

- Avenging Wrath (Maybe "Wings"?)
- Ancestral Guidance & Vampiric Embrace
- Mana Tide Totem
- Ancestral Protection Totem
- Mistweaver's Breath of Yu'lon / Chi-Ji ( https://www.wowhead.com/spell=322118/invoke-yulon-the-jade-serpent / https://www.wowhead.com/spell=325197/invoke-chi-ji-the-red-crane )

Thanks!

**Comment by PhenomDevel** [comment]
I didn't add a lot of supportive sounds because i am worried that they are easily overused and the raiders become spammed with sounds. That is something everyone using the sender has to keep in mind.

If you say those are commonly used i can add them no problem.

**Comment by Hayato2846** [comment]
Hey,

as most of these skill based sounds are on a 2-3 min CD they shouldn't be that spammable. Commonly used ranking (in my opinion) would be something like:

1. Wrath ( if you rly want to line up wings without anything like Ashen Hallow or Divine Toll )
2. Ancestral Protection Totem ( 5 Minute CD so not that rotational as usual 1, 2, 3 Minute CDs. Timing super important )
3. Mana Tide Totem ( Innervate like utility that should be used in the same way - free mana always appreciated )
4. Ancestral Guidance & Vampiric Embrace (same category as Rallying Cry / AMZ)
5. Mistweaver's Breath of Yu'lon / Chi-Ji (I think these are not that commonly used)


I use sounds as an audio support feedback for most of my assigned CDs so it's mostly 1/2/3 Sounds in a rotational 2 or 3 Minutes window. I think you're right to prevent too much spammable sounds but in the end it's a sender decision and additional sounds would support the customizable quality of messages.

**Comment by PhenomDevel** [comment]
2.4.4 includes more media files. :)
