### ISSUE TITLE
Duplicate file in zip - AceGUIwidget-DropDown.lua

### ISSUE THREAD

**Issue by boktai1000** [PhenomDevel/PhenomRaidTools#34]
**Describe the bug**
There appears to be two of the same file, AceGUIwidget-DropDown.lua - in the download for PhenomRaidTools-2.17.15-bcc.zip

**To Reproduce**
Extract contents of latest zip using something like 7-zip. At least PhenomRaidTools-2.17.15-bcc.zip appears to be affected - possibly other releases as well though.

**Expected behavior**
The file should extract and not have any duplicate files inside asking to override themselves

**Screenshots**
![image](https://user-images.githubusercontent.com/9054563/123173861-dddc5080-d444-11eb-9201-d5825be3af53.png)

**Additional context**
I manually download / install addons - and this is something of an irregularlity. I don't know how it may interact with updaters such as Overwolf/WowUp - but for sure this appears to be a problem for manual updaters like myself.

Thanks for looking into it!

**Comment by PhenomDevel** [comment]
From where did you manually download the release? Github, CurseForge or Wago? :) 

Asking because i couldn't reproduce this behaviour. Maybe you still had a PhenomRaidTools Folder in your Downloads folder and therefore it tried to overwrite?

**Comment by boktai1000** [comment]
This was on Curseforge - https://www.curseforge.com/wow/addons/phenomraidtools/download/3359015

Look inside the folder of the zip in PhenomRaidTools\Libs\AceGUI-3.0\widgets\ - there's duplicate files for a number of these with upper and lower case characters. 7-zip is able to see these duplicate files. I was able to replicate this behavior, and there is no folder in my Downloads folder

![image](https://user-images.githubusercontent.com/9054563/123271316-520b0880-d4c6-11eb-80b6-7812d38c58ab.png)

**Comment by PhenomDevel** [comment]
Yeah ok i believe i know why. I'll fix this in the curseforge packaging

**Comment by PhenomDevel** [comment]
This had to do with the configured URLs of the bigwigs packager. I removed them completly because all libs are embedded anyways.

Should be fixed in 2.18.5

**Comment by boktai1000** [comment]
I checked 2.18.5 and it looked good! Thank you!
