### ISSUE TITLE
Link to PhenomRaidTools Beginner Guide is broken (CurseForge)

### ISSUE THREAD

**Issue by boktai1000** [PhenomDevel/PhenomRaidTools#35]
**Describe the bug**
On the web page https://www.curseforge.com/wow/addons/phenomraidtools - the link to https://github.com/PhenomDevel/PhenomRaidTools/blob/master/doc/PhenomRaidTools_Beginner_Guide.pdf leads to a 404

**To Reproduce**
- Go to CurseForge website
- Click the link to the Beginner Guide

**Expected behavior**
Guide will open

**Screenshots**

![image](https://user-images.githubusercontent.com/9054563/123289416-1415e080-d4d6-11eb-956e-02fc73cd3124.png)

**Comment by PhenomDevel** [comment]
Should be working again

**Comment by boktai1000** [comment]
Just tried it myself, and it was not working.

Edit: Nevermind, 

- https://github.com/PhenomDevel/PhenomRaidTools/blob/master/doc/PhenomRaidTools_Beginner_Guide.pdf
- https://github.com/PhenomDevel/PhenomRaidTools/blob/master/docs/PhenomRaidTools_Beginner_Guide.pdf

The only link being /doc/ and the new being /docs/ - it appears that the new link is working now. Thank you!
