### ISSUE TITLE
Classic version - Wrong IDs and so on. 

### ISSUE THREAD

**Issue by knotteliten** [PhenomDevel/PhenomRaidTools#42]
The default raid encounter IDs do not match the classic client and they will fail to load.

**To Reproduce**
1. Encounter, click on new, select encounter and it shows the encounter IDs for Retail. 

**Expected behavior**
Expected the Encounter ID in preset to be correct

**Screenshots**

**Comment by PhenomDevel** [comment]
Should be fixed in 2.36.2
