### ISSUE TITLE
(Classic) Phenom Disabled inside raids, due to Current difficulty nil

### ISSUE THREAD

**Issue by knotteliten** [PhenomDevel/PhenomRaidTools#43]
**Describe the bug**
For Classic version of the addon, whenever you enter a raid with debug enabled, we get a message saying that the current difficulty is 176 - nil
I know the Classic and Retail difficulty variables are not equal, which might be some of the reason this acts up. 
As a resault, PRT wont load inside Ulduar 25 when tested.

**To Reproduce**
1. Enable Debug Mode
2. Enter Ulduar on 25 man
3. Read debug message

**Expected behavior**
What I expected was for PRT to load, and after changing encounter ids to classic Ids they would trigger. But as the addon wont load inside the zone at all, we end up with nothing. 

**Screenshots**
<img width="231" alt="difficulty" src="https://user-images.githubusercontent.com/17763186/215363292-ff015fd9-8999-4d12-8ee2-85284b905c14.png">

**Additional context**
As with Encounter IDs, Classic operates of different IDs for bosses , encounters and difficulty, as per say Ulduar falls into the category of 176 for 25 Man mode, 175 for 10 man mode. 
Sry prior mislabeled Bug repport.

**Comment by knotteliten** [comment]
Fixed the issue by going into Eventhandler, and changing the difficulty IDs for Wrath based on this list: 
https://wowpedia.fandom.com/wiki/DifficultyID (classic one further down)

**Comment by PhenomDevel** [comment]
If you already fixed so it works you could push a pull request so I don't have to do it again :)

**Comment by PhenomDevel** [comment]
Pull request is merged. Will be present in 2.36.1

**Comment by knotteliten** [comment]
Perfect! Amazing work btw on the addon, truely love it!

man. 30. jan. 2023 kl. 18:10 skrev Kevin ***@***.***>:
